### ISSUE TITLE
Move repo to STScI 

### ISSUE THREAD

**Issue by jotaylor** [jotaylor/SPAMM#23]
We need to move the repo to either myself or @gisederosa 's personal account, then that person will transfer it to STScI's account.

**Comment by antking** [comment]
I had to make the repository public but I have no transferred it to Jo's account.

**Comment by jotaylor** [comment]
@antking I didn't accept the transfer fast enough so it expired. Can you try again?

**Comment by jotaylor** [comment]
@gisederosa are going to discuss this issue further. For now, the repo has been moved to my account.

**Comment by jotaylor** [comment]
We've agreed to leave the repo where it is for now.
